import {FlightFX} from './flight-fx';
import {VolumeFX,type ImpactVisual} from './volume-fx';
import * as T from 'three';
import type {CardVisual} from './presentation';
/** Replaceable 3D presentation layer. Collision and card counts remain in the simulation. */
export class CardStage{
 private renderer=new T.WebGLRenderer({alpha:true,antialias:!matchMedia("(pointer:coarse)").matches});private scene=new T.Scene();private camera=new T.PerspectiveCamera(38,1,.1,3000);private objects=new Map<CardVisual,T.Mesh>();private mats=new Map<string,T.Material[]>();private geometry=new T.BoxGeometry(1,1,.035);private fx=new VolumeFX(this.scene);private flight=new FlightFX(this.scene);private last=0;private width=0;private height=0;
 constructor(parent:HTMLElement){const el=this.renderer.domElement;el.id='cards-3d';el.style.cssText='position:absolute;inset:0;pointer-events:none;z-index:1';parent.appendChild(el);this.renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia("(pointer:coarse)").matches?1.3:1.7));this.renderer.setClearColor(0,0);this.camera.position.z=1000;this.scene.add(new T.AmbientLight(0xffecd6,2));const key=new T.DirectionalLight(0xffffff,3);key.position.set(-200,350,700);this.scene.add(key);const rim=new T.DirectionalLight(0x86bcbf,1.2);rim.position.set(400,-200,200);this.scene.add(rim);}
 private materials(card:CardVisual['card']){const id=card.rank+':'+card.suit;let cached=this.mats.get(id);if(cached)return cached;const canvas=document.createElement('canvas');canvas.width=192;canvas.height=272;const c=canvas.getContext('2d')!;c.fillStyle='#fff1d2';c.fillRect(0,0,192,272);c.strokeStyle='#584231';c.lineWidth=3;c.strokeRect(6,6,180,260);c.strokeStyle='#b49b72';c.lineWidth=1;c.strokeRect(11,11,170,250);c.fillStyle=card.suit%2?'#a53236':'#243139';const label=card.rank===1?'A':card.rank===11?'J':card.rank===12?'Q':card.rank===13?'K':String(card.rank);c.font='bold 43px Georgia';c.fillText(label,20,52);c.font='26px Georgia';c.fillText(['♠','♥','♣','♦'][card.suit],22,84);c.textAlign='center';c.font='100px Georgia';c.fillText(['♠','♥','♣','♦'][card.suit],96,179);c.save();c.translate(192,272);c.rotate(Math.PI);c.textAlign='left';c.font='bold 34px Georgia';c.fillText(label,20,48);c.restore();const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;
 const face=new T.MeshStandardMaterial({map:tex,roughness:.83,metalness:0});const side=new T.MeshStandardMaterial({color:0xc4a980,roughness:.95});const backCanvas=document.createElement('canvas');backCanvas.width=192;backCanvas.height=272;const bc=backCanvas.getContext('2d')!;bc.fillStyle='#583f4a';bc.fillRect(0,0,192,272);bc.strokeStyle='#d0b187';bc.lineWidth=5;bc.strokeRect(10,10,172,252);bc.translate(96,136);bc.rotate(Math.PI/4);bc.strokeRect(-45,-45,90,90);bc.strokeRect(-29,-29,58,58);const backTexture=new T.CanvasTexture(backCanvas);backTexture.colorSpace=T.SRGBColorSpace;const back=new T.MeshStandardMaterial({map:backTexture,roughness:.85});cached=[side,side,side,side,face,back];this.mats.set(id,cached);return cached;}
 render(cards:CardVisual[],rings:ImpactVisual[],time:number,W:number,H:number){if(W!==this.width||H!==this.height){this.width=W;this.height=H;this.renderer.setSize(W,H);this.camera.aspect=W/H;this.camera.position.set(W/2,H/2,H/(2*Math.tan(19*Math.PI/180)));this.camera.updateProjectionMatrix();}const live=new Set(cards);for(const [s,m]of this.objects)if(!live.has(s)){this.scene.remove(m);this.objects.delete(s);}for(const s of cards){let m=this.objects.get(s);if(!m){m=new T.Mesh(this.geometry,this.materials(s.card));this.objects.set(s,m);this.scene.add(m);}m.visible=s.age>=0;const depth=42+Math.sin(s.age*6+s.index*1.7)*32+s.index*3,d=this.camera.position.z,k=(d-depth)/d;m.position.set(W/2+(s.x-W/2)*k,H/2+(H/2-s.y)*k,depth);m.scale.set(s.size,s.size*1.4,s.size);const flip=s.age*(s.type==='blade'?8:s.type==='blast'?11:5);m.rotation.set(s.type==='flight'?.45+(s.bank??0):flip+s.index*.65,s.type==='flower'?s.age*4+s.index*.7:Math.sin(s.age*6+s.index)*.95,-s.rotation+Math.sin(s.age*3)*.18);}
 this.flight.update(new Set(cards.filter(s=>s.formation&&!s.detached).map(s=>s.formation!)),H);
 for(const r of rings)this.fx.impact(r,H);const dt=Math.min(.04,Math.max(0,time-this.last));this.last=time;this.fx.update(dt);
 this.renderer.render(this.scene,this.camera);}
}
