import {enemyTypes,wavePlan,kindFor,type EnemyKind} from './enemies';
import {advanceFormation,formationSlot,type Formation} from './formations';
import {CardStage} from './card-stage';
import {PaperMusic} from './music';
import {paperPresentation} from './presentation';
import {analyze, type Card, type PokerPattern} from './combat-rules';
import './style.css';
import {planMove,type Plan} from './expert';

const $=(id:string)=>document.getElementById(id)!;
const suits=['♠','♥','♣','♦'];
const label=(n:number)=>n===1?'A':n===11?'J':n===12?'Q':n===13?'K':String(n);
const app=$('app');
app.innerHTML=`<main><section id="arena"><canvas id="battle"></canvas><header><div class="logo">甩<span>牌</span><small>CARD / RUSH</small></div><div class="scores"><span>尸潮 <b id="wave">01</b></span><span>击破 <b id="kills">0</b></span><span>防线 <b id="lives">20</b></span><button id="pause" aria-label="暂停">Ⅱ</button></div></header><div id="announcer"></div><div id="gesture-hint">装填完成后，在战场上划一下甩出</div><div id="attack-label"></div></section><section id="console"><div class="console-top"><span id="step"></span><span id="next"></span></div><div id="weapon"><div class="weapon-title"><small>本次攻击</small><strong id="weapon-name"></strong><span id="weapon-tag"></span></div><div id="slots"></div></div><div class="hand-top"><div class="sorts"><span>整理</span><button data-sort="rank">顺子优先</button><button data-sort="pairs">对子优先</button><button data-sort="suit">同花优先</button></div><span id="selection">点选或滑选手牌，双击确认</span></div><div id="hand" role="group" aria-label="手牌"></div><div class="foot"><span>点选 / 滑选 → 双击确认 → 点牌填数 → 战场滑动发射</span><button id="help">玩法</button><button id="sound">声音 开</button></div></section></main><div id="overlay"><div class="intro"><div class="eyebrow">即时配牌 / 甩出火力</div><h1>把好牌，<br><em>打出去。</em></h1><p>点选或滑选一组手牌，双击确认装弹。<br>亮起的参数槽，点一张牌填入。<br>连击：划定方向后按住喷牌，松手停止。<br>重击：滑动后松手，整组牌重重甩出。</p><div class="rules"><span>单张 · 面值伤害</span><span>对子 / 三条 · 弹射追击</span><span>顺子 · 刃阵贯穿</span><span>同花 4 张起 · 花形散射</span><span>炸弹 / 葫芦 · 爆炸</span><span>散牌也能直接打</span></div><p class="muted">8 张手牌 · 用几张补几张 · 容器自动给定 · 无撤回<br>先打散牌熟悉动作，再留下关键牌凑组合。</p><button id="variety">观看多样打法演示 ↗</button><button id="demo">观看高手打法演示 ↗</button><button id="begin">开始甩牌 <span>↗</span></button></div></div>`;
const canvas=$('battle') as HTMLCanvasElement,ctx=canvas.getContext('2d')!;
const templates=[
 {name:'连击',tag:'划定方向后按住连发，松手结束',params:['最多轮数'],kind:'stream',before:'按住沿滑动方向发射，最多',after:'轮；松手停止。'},
 {name:'重击',tag:'划动瞄准，松手释放强化牌组',params:['威力档数'],kind:'heavy',before:'沿滑动方向甩出，威力提升',after:'档。'},
];
let tutorial=false,tutorialRound=0,tutorialEmission=0;
let serial=0,hand:Card[]=[],ammo:Card[]=[],params:Card[]=[],chosen=new Set<number>();
let phase:'ammo'|'param'|'ready'='ammo',turn=0,pattern:PokerPattern|null=null;
let active=false,paused=false,sound=true,time=0,kills=0,lives=20,wave=1,spawned=0,spawnCD=.6,between=0,shotCount=0,emitted=0;
let W=1,H=1,shake=0,flash=0,announceTimer=0,aim:{x:number;y:number;ex:number;ey:number}|null=null;
const music=new PaperMusic();
const skin=paperPresentation;
let cardStage:CardStage|null=null;try{cardStage=new CardStage($('arena'));}catch{console.warn('WebGL unavailable; using painted cards.');}
const rand=(a:number,b:number)=>a+Math.random()*(b-a);
function beep(f=500,_d=.04,_v=.025){if(sound)music.cue(f>=900?'ready':f>=700?'load':'select',Math.max(1,(f-400)/35));}

function deal():Card{return {id:++serial,rank:1+Math.floor(Math.random()*13),suit:Math.floor(Math.random()*4)};}
function weapon(){return templates[turn%templates.length];}
function escapedCard(c:Card){return `${label(c.rank)}${suits[c.suit]}`;}
function patternTitle(p:PokerPattern|null){if(!p)return '';return p.id==='high'&&ammo.length===1?'单张':p.name;}
function bulletType(p:PokerPattern){if(['bomb','chain-bomb','full-house','four-single','four-pair'].includes(p.id))return 'blast';if(p.id.startsWith('airplane'))return 'flight';if(p.id.includes('flush'))return 'flower';if(['straight','pair-run'].includes(p.id))return 'blade';if(['pair','two-pair','triple','triple-single'].includes(p.id))return 'echo';return 'card';}
const colors:Record<string,string>={card:'#35474c',echo:'#795c86',blade:'#377d74',flower:'#ba5068',blast:'#cb6239',flight:'#456c91'};
function totalDamage(){return ammo.reduce((s,c)=>s+c.rank,0)*(pattern?.factor??1);}
function renderHand(){ $('hand').innerHTML=hand.map(c=>`<button class="card ${c.suit%2?'warm':'cool'}" data-id="${c.id}" aria-label="${escapedCard(c)}"><span class="corner">${label(c.rank)}<small>${suits[c.suit]}</small></span><span class="suit">${suits[c.suit]}</span><span class="corner lower">${label(c.rank)}</span></button>`).join('');$('hand').classList.toggle('locked',phase==='ready');}
function updateUI(){const w=weapon();$('weapon-name').textContent=w.name;$('weapon-tag').textContent=w.tag;$('next').textContent='下一招 · '+templates[(turn+1)%templates.length].name;
 $('step').textContent=phase==='ammo'?'01 / 划牌装弹':phase==='param'?`02 / 点牌填「${w.params[params.length]}」`:(w.kind==='stream'?'03 / 划定方向，按住连发':'03 / 滑动瞄准，松手重击');
 const ammoSlot=`<div class="slot ammo ${phase==='ammo'?'current':'filled'}"><small>弹药槽</small><strong>${ammo.length?ammo.map(escapedCard).join(' '):'选一张或一组牌'}</strong><span>${pattern?patternTitle(pattern)+' · '+Math.round(totalDamage())+' 基础伤害':'牌型决定攻击类型'}</span></div>`;
 const ps=w.params.map((n,i)=>`<div class="slot ${phase==='param'&&i===params.length?'current':''} ${params[i]?'filled':''}"><small>${n}</small><strong>${params[i]?params[i].rank:'？'}</strong><span>${params[i]?escapedCard(params[i]):'点一张牌'}</span></div>`);
 $('slots').innerHTML=`<span class="connector">将</span>${ammoSlot}<span class="connector">${w.before}</span>${ps[0]}<span class="connector">${w.after}</span>${ps[1]??''}${w.params.length>1?'<span class="connector">× 60 像素 / 秒。</span>':''}`;

 $('console').classList.toggle('ready',phase==='ready');$('gesture-hint').classList.toggle('visible',phase==='ready');$('selection').textContent=phase==='ammo'?'点选或滑选手牌，双击确认':phase==='param'?'点数字牌，自动填入亮起的槽':'已装填 · 去战场甩出去';
 $('gesture-hint').textContent=w.kind==='stream'?'划一下定方向 · 按住连发 · 松手停止':'划一下瞄准 · 松手重击';renderHand();updateTutorial();}
function announce(s:string){$('announcer').textContent=s;announceTimer=2.2;$('announcer').classList.add('show');}
function flyCards(ids:number[],slot:number){const dest=document.querySelectorAll<HTMLElement>('.slot')[slot]?.getBoundingClientRect();if(!dest)return;ids.forEach((id,i)=>{const el=document.querySelector<HTMLElement>(`[data-id="${id}"]`);if(!el)return;const r=el.getBoundingClientRect(),clone=el.cloneNode(true) as HTMLElement;clone.removeAttribute('data-id');clone.classList.remove('selected');Object.assign(clone.style,{position:'fixed',left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px',zIndex:'20',pointerEvents:'none',margin:'0'});document.body.appendChild(clone);const animation=clone.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${dest.left+dest.width/2-r.left-r.width/2+(i-(ids.length-1)/2)*9}px,${dest.top+dest.height/2-r.top-r.height/2}px) scale(.45)`,opacity:.15}],{duration:180,easing:'cubic-bezier(.2,.8,.2,1)'});animation.onfinish=()=>clone.remove();});}
function fillAmmo(){if(!chosen.size)return;const max=hand.length-weapon().params.length;if(chosen.size>max){announce('留 '+weapon().params.length+' 张牌填参数');chosen.clear();mark();return;}flyCards([...chosen],0);ammo=hand.filter(c=>chosen.has(c.id));pattern=analyze(ammo);hand=hand.filter(c=>!chosen.has(c.id));chosen.clear();phase='param';beep(760,.08);updateUI();}
function fillParam(id:number){const c=hand.find(c=>c.id===id);if(!c)return;flyCards([id],params.length+1);params.push(c);hand=hand.filter(c=>c.id!==id);beep(550+params.length*180,.06);if(params.length===weapon().params.length){phase='ready';beep(1000,.12);}$('slots').classList.remove('bump');void $('slots').offsetWidth;$('slots').classList.add('bump');updateUI();}
function mark(){if(phase==='ammo')$('selection').textContent='点选或滑选手牌，双击确认';document.querySelectorAll<HTMLElement>('[data-id]').forEach(el=>el.classList.toggle('selected',chosen.has(Number(el.dataset.id))));if(chosen.size){const cards=hand.filter(c=>chosen.has(c.id)),p=analyze(cards);$('selection').textContent=(cards.length===1?'单张':p.name)+' · '+chosen.size+' 张 · 双击确认，进入数字槽';}}
let selecting=false,startIndex=-1,paramDown:number|null=null;
let selectionBefore=new Set<number>(),dragged=false,downX=0,downY=0,lastTapId=-1,lastTapTime=0,confirmTap=false;
$('hand').addEventListener('pointerdown',e=>{if(!active||paused||phase==='ready')return;const el=(e.target as HTMLElement).closest<HTMLElement>('[data-id]');if(!el)return;e.preventDefault();$('hand').setPointerCapture(e.pointerId);const id=Number(el.dataset.id);if(phase==='param'){paramDown=id;return;}selecting=true;selectionBefore=new Set(chosen);startIndex=hand.findIndex(c=>c.id===id);downX=e.clientX;downY=e.clientY;dragged=false;confirmTap=id===lastTapId&&performance.now()-lastTapTime<350;if(!confirmTap){if(chosen.has(id))chosen.delete(id);else chosen.add(id);}mark();beep(430,.025);});
$('hand').addEventListener('pointermove',e=>{if(!selecting||Math.hypot(e.clientX-downX,e.clientY-downY)<8)return;dragged=true;confirmTap=false;const els=[...document.querySelectorAll<HTMLElement>('#hand [data-id]')];let idx=els.findIndex(el=>{const r=el.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right;});if(idx<0)idx=e.clientX<els[0].getBoundingClientRect().left?0:els.length-1;chosen=new Set([...selectionBefore,...hand.slice(Math.min(startIndex,idx),Math.max(startIndex,idx)+1).map(c=>c.id)]);mark();});
$('hand').addEventListener('pointerup',e=>{if($('hand').hasPointerCapture(e.pointerId))$('hand').releasePointerCapture(e.pointerId);if(selecting){selecting=false;if(confirmTap&&!dragged){chosen.add(hand[startIndex].id);lastTapId=-1;lastTapTime=0;fillAmmo();}else{lastTapId=dragged?-1:hand[startIndex].id;lastTapTime=performance.now();mark();}}else if(paramDown!==null){const id=paramDown;paramDown=null;fillParam(id);}});
$('hand').addEventListener('pointercancel',()=>{if(selecting)chosen=new Set(selectionBefore);selecting=false;paramDown=null;lastTapId=-1;mark();});
document.querySelectorAll<HTMLElement>('[data-sort]').forEach(b=>b.onclick=()=>{if(!active||paused||phase==='ready'||selecting)return;const mode=b.dataset.sort;const counts=new Map<number,number>();hand.forEach(c=>counts.set(c.rank,(counts.get(c.rank)??0)+1));hand.sort((a,b)=>mode==='pairs'?(counts.get(b.rank)!-counts.get(a.rank)!||a.rank-b.rank):mode==='suit'?(a.suit-b.suit||a.rank-b.rank):(a.rank-b.rank||a.suit-b.suit));document.querySelectorAll('[data-sort]').forEach(x=>x.classList.toggle('on',x===b));beep(350);renderHand();mark();});
interface Enemy{kind?:EnemyKind;x:number;y:number;hp:number;max:number;speed:number;seed:number;hit:number;}
interface Shot{formation:Formation;detached:boolean;bank:number;pattern:string;age:number;index:number;count:number;wobble:number;x:number;y:number;vx:number;vy:number;card:Card;type:string;color:string;damage:number;life:number;size:number;rotation:number;trail:{x:number;y:number}[];pierce:number;bounce:number;repeats:number;impact:number;radius:number;returnAt:number;returned:boolean;hits:Set<Enemy>;}
interface Particle{x:number;y:number;vx:number;vy:number;life:number;max:number;size:number;color:string;}
interface Ring{pattern?:string;x:number;y:number;r:number;max:number;life:number;color:string;}
interface Pending{pattern:string;at:number;angle:number;cards:Card[];type:string;color:string;damage:number;kind:string;range:number;strength:number;repeat:number;}
let formationName='横排推进';
const falls:{x:number;y:number;life:number;seed:number}[]=[];
const enemies:Enemy[]=[],shots:Shot[]=[],particles:Particle[]=[],rings:Ring[]=[],pending:Pending[]=[];
function burst(x:number,y:number,color:string,n:number,power=1){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),v=rand(35,160)*power;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.18,.48),max:.48,size:rand(1,3)*power,color});}}
function damage(e:Enemy,n:number){if(e.hp<=0)return;e.hp-=n;e.hit=.13;music.cue('hit');if(e.hp<=0){kills++;music.cue('kill');falls.push({x:e.x,y:e.y,life:.45,seed:e.seed});$('kills').textContent=String(kills);burst(e.x,e.y,'#526d58',8);if(e.kind==='volatile'){rings.push({pattern:'bomb',x:e.x,y:e.y,r:8,max:100,life:.4,color:'#be743a'});for(const q of enemies)if(q!==e&&q.hp>0&&Math.hypot(q.x-e.x,q.y-e.y)<100)damage(q,22+wave*3);}}}
let stream:{shot:Pending;left:number;next:number}|null=null;
let gestureUsed=false;
function finishAttack(){const tutorialDidFire=emitted>tutorialEmission;const refill=ammo.length+params.length;for(let i=0;i<refill;i++)hand.push(deal());ammo=[];params=[];pattern=null;phase='ammo';turn++;stream=null;if(tutorial&&tutorialDidFire){tutorialRound++;if(tutorialRound>=2){endTutorial();return;}tutorialEmission=emitted;announce('第二步：重击，滑动后松手释放');}updateUI();}
function shotFeedback(p:Pending){const onBeat=music.cue('fire',p.kind==='heavy'?p.repeat:1);if(onBeat){$('step').classList.remove('beat');void $('step').offsetWidth;$('step').classList.add('beat');}flash=p.kind==='heavy'?.19:.06;shake=p.kind==='heavy'?5+p.repeat*.45:2;burst(W/2,H-35,p.color,p.kind==='heavy'?28:8,1+p.strength);}
function fire(angle:number){if(!pattern)return;if(tutorial)tutorialEmission=emitted;const type=bulletType(pattern),color=colors[type],strength=Math.min(1,ammo.reduce((s,c)=>s+c.rank,0)/52),w=weapon();const repeat=params[0].rank;
 const p:Pending={pattern:pattern.id,at:time,angle,cards:[...ammo],type,color,damage:totalDamage(),kind:w.kind,range:0,strength,repeat};
 shotCount++;$('attack-label').textContent=`${patternTitle(pattern)} / ${w.name} · ${repeat}${w.kind==='stream'?'轮上限':'档'}`;$('attack-label').style.color=color;$('attack-label').classList.remove('pop');void $('attack-label').offsetWidth;$('attack-label').classList.add('pop');
 if(w.kind==='stream'){stream={shot:p,left:repeat,next:time};}else{emit(p);shotFeedback(p);finishAttack();}}
canvas.addEventListener('pointerdown',e=>{if(!active||paused||phase!=='ready')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);gestureUsed=false;const r=canvas.getBoundingClientRect();aim={x:e.clientX-r.left,y:e.clientY-r.top,ex:e.clientX-r.left,ey:e.clientY-r.top};});
canvas.addEventListener('pointermove',e=>{if(!aim)return;const r=canvas.getBoundingClientRect();aim.ex=e.clientX-r.left;aim.ey=e.clientY-r.top;const dx=aim.ex-aim.x,dy=aim.ey-aim.y;if(Math.hypot(dx,dy)>=12&&!gestureUsed&&weapon().kind==='stream'){gestureUsed=true;fire(Math.atan2(dy,dx));}if(stream)stream.shot.angle=Math.atan2(dy,dx);});
function release(){if(!aim)return;const dx=aim.ex-aim.x,dy=aim.ey-aim.y;aim=null;if(stream){finishAttack();return;}if(gestureUsed)return;if(Math.hypot(dx,dy)<12){announce('划一下再松手');return;}fire(Math.atan2(dy,dx));}
canvas.addEventListener('pointerup',e=>{release();if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);});
canvas.addEventListener('pointercancel',()=>{aim=null;if(stream)finishAttack();});
function emit(p:Pending){emitted+=p.cards.length;const ordered=p.pattern==='full-house'?[...p.cards].sort((a,b)=>p.cards.filter(c=>c.rank===b.rank).length-p.cards.filter(c=>c.rank===a.rank).length):p.cards;p={...p,cards:ordered};const n=p.cards.length,formation:Formation={pattern:p.pattern,count:n,x:W/2,y:H-35,angle:p.angle,age:0,turn:0,detonated:false},speed=620,boost=p.kind==='heavy'?1+p.repeat*.22:1;
 for(let i=0;i<n;i++){const spread=p.pattern==='straight-flush'?.09:p.type==='flower'?.16:p.type==='blade'?.025:.045;const a=p.angle+(i-(n-1)/2)*spread;shots.push({formation,detached:false,bank:0,pattern:p.pattern,age:0,index:i,count:n,wobble:0,x:W/2+Math.cos(a+Math.PI/2)*(i-(n-1)/2)*19,y:H-35,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,card:p.cards[i],type:p.type,color:p.color,damage:p.damage/n*boost,life:H/speed+2,size:(25+p.strength*13)*Math.sqrt(boost),rotation:a+Math.PI/2,trail:[],pierce:p.type==='blade'||p.pattern==='straight-flush'?Math.max(2,n):p.type==='flower'?1:0,bounce:p.type==='echo'?Math.max(1,n-1):0,repeats:0,impact:p.kind==='heavy'?p.repeat:0,radius:(45+p.cards[i].rank*3)*Math.sqrt(boost),returnAt:0,returned:false,hits:new Set()});}
 rings.push({pattern:p.pattern,x:W/2,y:H-35,r:5,max:(50+p.strength*50)*Math.sqrt(boost),life:.3,color:p.color});}

function step(dt:number){time+=dt;music.update(dt);if(demoMode)demoStep();if(stream&&time>=stream.next){emit(stream.shot);shotFeedback(stream.shot);stream.left--;stream.next=time+.13;$('gesture-hint').textContent='连发中 · 剩余 '+stream.left+' 轮 · 松手停止';if(stream.left<=0)finishAttack();}announceTimer-=dt;if(announceTimer<0)$('announcer').classList.remove('show');shake=Math.max(0,shake-dt*25);flash=Math.max(0,flash-dt);
 const plan=wavePlan(wave),limit=plan.total;if(!tutorial&&spawned<limit){spawnCD-=dt;if(spawnCD<=0){spawnCD=plan.interval;const count=Math.min(plan.group,limit-spawned),formation=(wave+Math.floor(spawned/4))%4,center=rand(W*.25,W*.75);for(let j=0;j<count;j++){const kind=kindFor(wave,spawned+j),spec=enemyTypes[kind],hp=(9+wave*3)*spec.hp,x=formation===0?W*.2+j*W*.2:formation===1?center:formation===2?center+(j%2)*32-16:rand(W*.12,W*.88),y=formation===1?-20-j*45:formation===2?-20-Math.floor(j/2)*32:-20;enemies.push({kind,x:Math.min(W-25,Math.max(25,x)),y,hp,max:hp,speed:plan.speed*spec.speed+rand(0,2),seed:rand(0,6),hit:0});}spawned+=count;formationName=['横排推进','纵列突破','密集团簇','散兵逼近'][formation];}}else if(!tutorial&&!enemies.length){between+=dt;if(between>1.5){wave++;spawned=0;spawnCD=3;between=0;$('wave').textContent=String(wave).padStart(2,'0');const intro=wave===2?'runner':wave===3?'brute':wave===4?'armored':wave===5?'volatile':null;announce('第 '+wave+' 波'+(intro?' · '+enemyTypes[intro].name+'：'+enemyTypes[intro].tip:''));}}

 for(let i=pending.length-1;i>=0;i--)if(pending[i].at<=time){emit(pending[i]);pending.splice(i,1);}
 for(const e of enemies){e.y+=e.hit>0?-dt*20:e.speed*dt;if(e.kind==='runner')e.x=Math.max(25,Math.min(W-25,e.x+Math.sin(time*4+e.seed)*dt*12));e.hit=Math.max(0,e.hit-dt);if(e.y>H-22&&e.hp>0){e.hp=0;lives--;$('lives').textContent=String(lives);shake=5;burst(e.x,H-22,'#ff638a',12);}}
 const liveFormations=new Set(shots.filter(s=>!s.detached).map(s=>s.formation));for(const f of liveFormations)advanceFormation(f,dt,enemies);
 for(const s of shots){s.age+=dt;s.life-=dt;s.trail.push({x:s.x,y:s.y});if(s.trail.length>9)s.trail.shift();const ox=s.x,oy=s.y;if(!s.detached){const slot=formationSlot(s.formation,s.index);s.x=slot.x;s.y=slot.y;s.rotation=slot.rotation;s.bank=slot.bank;s.vx=Math.cos(s.formation.angle)*620;s.vy=Math.sin(s.formation.angle)*620;}else{s.x+=s.vx*dt;s.y+=s.vy*dt;}
 for(const e of enemies){if(e.hp<=0||s.hits.has(e))continue;const dx=s.x-ox,dy=s.y-oy,t=Math.max(0,Math.min(1,((e.x-ox)*dx+(e.y-oy)*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(e.x-ox-dx*t,e.y-oy-dy*t)<s.size*.6+12){s.hits.add(e);s.detached=true;damage(e,s.damage*(e.kind==='armored'&&!['blade','blast','flight'].includes(s.type)?.55:1));burst(e.x,e.y,s.color,11+s.impact,1.2+s.impact*.05);if(s.type!=='blast'&&s.type!=='flight'){rings.push({pattern:s.pattern,x:e.x,y:e.y,r:6,max:42+s.impact*5,life:.28,color:s.color});shake=Math.max(shake,Math.min(7,s.impact*.45));}if((s.type==='blast'||s.type==='flight')&&(!['bomb','chain-bomb'].includes(s.pattern)||!s.formation.detonated)){s.formation.detonated=true;const radius=s.radius;rings.push({pattern:s.pattern,x:e.x,y:e.y,r:8,max:radius,life:.4,color:s.color});for(const q of enemies)if(q!==e&&Math.hypot(q.x-e.x,q.y-e.y)<radius)damage(q,s.damage*.8*(['bomb','chain-bomb'].includes(s.pattern)?s.count:1));burst(e.x,e.y,s.color,25,1.9);shake=Math.max(shake,3);}
 if(s.repeats>0||s.bounce>0){if(s.repeats>0)s.repeats--;else s.bounce--;const target=enemies.filter(q=>q.hp>0&&q!==e).sort((a,b)=>(Math.hypot(a.x-s.x,a.y-s.y)-(Math.sign(a.x-e.x)===(s.index%2?1:-1)?100:0))-(Math.hypot(b.x-s.x,b.y-s.y)-(Math.sign(b.x-e.x)===(s.index%2?1:-1)?100:0)))[0];if(target){s.hits.clear();s.hits.add(e);const a=Math.atan2(target.y-s.y,target.x-s.x);s.vx=Math.cos(a)*570;s.vy=Math.sin(a)*570;s.rotation=a+Math.PI/2;}else s.life=0;}else if(s.pierce>0)s.pierce--;else s.life=0;
 break;}}}
 for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0||shots[i].x<-100||shots[i].x>W+100||shots[i].y<-100||shots[i].y>H+100)shots.splice(i,1);
 for(let i=enemies.length-1;i>=0;i--)if(enemies[i].hp<=0)enemies.splice(i,1);
 for(let i=falls.length-1;i>=0;i--){falls[i].life-=dt;if(falls[i].life<=0)falls.splice(i,1);}
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;if(p.life<=0)particles.splice(i,1);}
 for(let i=rings.length-1;i>=0;i--){rings[i].life-=dt;rings[i].r+=(rings[i].max-rings[i].r)*dt*10;if(rings[i].life<=0)rings.splice(i,1);}
 if(lives<=0){active=false;music.setPaused(true);showEnd();}}
function line(x1:number,y1:number,x2:number,y2:number,color:string,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function draw(){const status=music.status() as {state:string;energy:number};$('audio-start').hidden=status.state==='running'||!sound||!active;$('arena').style.setProperty('--energy',String(status.energy));$('takeover').hidden=!demoMode;ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#e9dabb');bg.addColorStop(1,'#d8c49e');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(rand(-shake,shake),rand(-shake,shake));
 // Muted painted silhouettes frame a clear paper playfield.
 for(const side of [-1,1]){ctx.save();if(side===1){ctx.translate(W,0);ctx.scale(-1,1);}for(let i=0;i<6;i++){const x=i*22-30,y=H*.16+(i%3)*46;ctx.fillStyle=i%2?'#6f70751b':'#655c7020';ctx.beginPath();ctx.moveTo(x,H-20);ctx.lineTo(x,y+30);ctx.lineTo(x+13,y);ctx.lineTo(x+38,y+20);ctx.lineTo(x+42,H-20);ctx.fill();ctx.fillStyle='#bc785718';ctx.beginPath();ctx.moveTo(x+13,y);ctx.lineTo(x+38,y+20);ctx.lineTo(x+42,H-20);ctx.lineTo(x+24,H-20);ctx.fill();}ctx.restore();}
 const glow=ctx.createRadialGradient(W/2,H,10,W/2,H,W*.6);glow.addColorStop(0,'#af744420');glow.addColorStop(1,'#af744400');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);
 line(0,H-18,W,H-18,'#69553b88',2);for(let x=12;x<W;x+=28)line(x,H-18,x+8,H-10,'#69553b55');
 for(const f of falls){ctx.save();ctx.translate(f.x,f.y);ctx.rotate((.45-f.life)*3*(f.seed>3?1:-1));ctx.globalAlpha=f.life/.45;skin.drawEnemy(ctx,{x:0,y:0,hp:0,max:1,hit:0,seed:f.seed},time);ctx.restore();}
 for(const e of enemies)skin.drawEnemy(ctx,e,time);
 if(!cardStage)for(const s of shots)if(s.age>=0)skin.drawCard(ctx,s);
 ctx.globalCompositeOperation='multiply';for(const r of rings)if(!cardStage)skin.drawImpact(ctx,r.x,r.y,r.r,r.color,r.pattern??'high',Math.min(1,r.life*3));for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size*2,p.size);}ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';
 const ready=phase==='ready',col=ready?colors[bulletType(pattern!)]:'#66503a';ctx.save();ctx.translate(W/2,H-35);ctx.strokeStyle=col;ctx.lineWidth=2;ctx.shadowColor=col;ctx.shadowBlur=0;ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(22,10);ctx.lineTo(0,3);ctx.lineTo(-22,10);ctx.closePath();ctx.stroke();if(ready){ctx.rotate(Math.sin(time*2)*.04);ammo.slice(0,8).forEach((c,i)=>{const x=(i-(Math.min(ammo.length,8)-1)/2)*12;ctx.fillStyle='#f8eed7';ctx.fillRect(x-8,-42,16,24);ctx.strokeRect(x-8,-42,16,24);ctx.fillStyle=col;ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText(label(c.rank),x,-26);});}ctx.restore();
 if(aim){const dx=aim.ex-aim.x,dy=aim.ey-aim.y,a=Math.atan2(dy,dx);ctx.setLineDash([8,7]);line(W/2,H-35,W/2+Math.cos(a)*H,H-35+Math.sin(a)*H,col,2);ctx.setLineDash([]);line(aim.x,aim.y,aim.ex,aim.ey,'#46382d',3);ctx.beginPath();ctx.arc(aim.x,aim.y,6,0,Math.PI*2);ctx.strokeStyle='#46382d';ctx.stroke();}
 if(flash>0){ctx.fillStyle=`rgba(255,243,214,${flash*.22})`;ctx.fillRect(0,0,W,H);}ctx.restore();cardStage?.render(shots,rings,time,W,H);}
function resize(){const r=$('arena').getBoundingClientRect(),oldW=W,oldH=H;W=r.width;H=r.height;const d=Math.min(devicePixelRatio,2);canvas.width=W*d;canvas.height=H*d;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0);if(oldW>1)for(const e of enemies){e.x*=W/oldW;e.y*=H/oldH;}}
function start(){tutorial=!demoMode&&!new URLSearchParams(location.search).has('qa');tutorialRound=0;void music.unlock();hand=[3,3,4,5,6,8,8,13].map((rank,i)=>({id:++serial,rank,suit:i%4}));active=true;paused=false;$('overlay').hidden=true;if(tutorial){enemies.length=0;for(let i=0;i<3;i++)enemies.push({x:W/2+(i-1)*65,y:H*.38,hp:9999,max:9999,speed:0,seed:i,hit:0});}updateUI();announce(tutorial?'练习场 · 敌人不会前进':'第 1 波 · 划牌，装填，甩出去');beep(660,.12);}
function updateTutorial(){const box=$('tutorial');if(!box)return;box.hidden=!tutorial;if(!tutorial)return;const action=phase==='ammo'?'点选或滑选一组手牌，双击确认装弹。':phase==='param'?'点一张剩余手牌，填进亮起的数字槽。':tutorialRound===0?'在战场向上划，保持按住连发，再松手。':'在战场向上划，松手释放重击。';$('tutorial-copy').textContent=`${tutorialRound+1}/2 · ${tutorialRound===0?'连击练习':'重击练习'}：${action}`;}
function endTutorial(){tutorial=false;tutorialRound=2;enemies.length=0;shots.length=0;rings.length=0;stream=null;aim=null;ammo=[];params=[];pattern=null;phase='ammo';turn=0;wave=1;kills=0;spawned=0;spawnCD=4;hand=[3,3,4,5,6,8,8,13].map((rank,i)=>({id:++serial,rank,suit:i%4}));$('kills').textContent='0';updateUI();announce('练习完成 · 第 1 波将在 4 秒后开始');}
const tutorialBox=document.createElement('div');tutorialBox.id='tutorial';tutorialBox.hidden=true;tutorialBox.innerHTML='<span id="tutorial-copy"></span><button id="skip-tutorial">跳过练习</button>';$('console').prepend(tutorialBox);$('skip-tutorial').onclick=endTutorial;
function showEnd(){$('overlay').hidden=false;$('overlay').innerHTML=`<div class="intro"><div class="eyebrow">本轮结束</div><h1>打出 ${shotCount} 手<br><em>击破 ${kills} 只。</em></h1><p>抵达第 ${wave} 波。再试一次不同的留牌方式。</p><button id="restart">再来一局 ↗</button></div>`;$('restart').onclick=()=>location.reload();}
$('variety').onclick=()=>{varietyMode=true;demoMode=true;start();};$('begin').onclick=start;$('demo').onclick=()=>{demoMode=true;start();announce('高手演示 · 实际手牌 / 无额外伤害 / 可随时接管');};$('pause').onclick=()=>{if(!active)return;paused=!paused;music.setPaused(paused);if(paused){aim=null;if(stream)finishAttack();}$('pause').textContent=paused?'▶':'Ⅱ';$('gesture-hint').textContent=paused?'已暂停 · 点击右上角继续':'装填完成后，在战场上划一下甩出';$('gesture-hint').classList.toggle('visible',paused||phase==='ready');};
$('help').onclick=()=>{if(!active)return;paused=true;music.setPaused(true);$('pause').textContent='▶';announce('划牌松手装弹 → 点牌填亮槽 → 战场滑动发射。点右上角继续。');};$('sound').onclick=()=>{sound=!sound;music.setEnabled(sound);if(sound)void music.unlock();$('sound').textContent='声音 '+(sound?'开':'关');};
let varietyMode=new URLSearchParams(location.search).get('demo')==='variety';
let demoMode=false,demoNext=0,demoStage=0,demoPlan:Plan|null=null;
const demoHistory:{pattern:string;reason:string;turn:number}[]=[];
function demoStep(){if(time<demoNext||paused||!active)return;
 if(demoStage===0){if(!enemies.some(e=>e.y>60)){demoNext=time+.25;return;}demoPlan=planMove(hand,enemies,W,H,weapon().kind,varietyMode?demoHistory.slice(-8).map(h=>h.pattern):undefined);if(!demoPlan)return;const order=new Map(demoPlan.order.map((id,i)=>[id,i]));hand.sort((a,b)=>order.get(a.id)!-order.get(b.id)!);renderHand();chosen=new Set(demoPlan.ammo);mark();announce((varietyMode?'多样演示：':'演示：')+demoPlan.reason);demoHistory.push({pattern:demoPlan.pattern,reason:demoPlan.reason,turn});demoStage=1;demoNext=time+.32;
 }else if(demoStage===1){fillAmmo();demoStage=2;demoNext=time+.18;
 }else if(demoStage===2){fillParam(demoPlan!.param);demoStage=3;demoNext=time+.22;
 }else if(demoStage===3){const a=demoPlan!.angle;aim={x:W/2,y:H*.7,ex:W/2+Math.cos(a)*100,ey:H*.7+Math.sin(a)*100};fire(a);demoStage=4;demoNext=time+(weapon().kind==='stream'?.25:.15);
 }else{if(stream){const target=enemies.filter(e=>e.hp>0).sort((a,b)=>b.y-a.y)[0];if(target)stream.shot.angle=Math.atan2(target.y-(H-35),target.x-W/2);demoNext=time+.08;return;}aim=null;demoStage=0;demoNext=time+.12;}}
const takeover=document.createElement('button');takeover.textContent='接管 / 退出演示';takeover.id='takeover';takeover.onclick=()=>{demoMode=false;demoStage=0;chosen.clear();aim=null;if(stream)finishAttack();mark();announce('已接管，继续当前手牌');};$('arena').appendChild(takeover);const audioStart=document.createElement('button');audioStart.id='audio-start';audioStart.textContent='点击开启背景音乐';audioStart.onclick=()=>void music.unlock();$('arena').appendChild(audioStart);
new ResizeObserver(resize).observe($('arena'));addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused)$('pause').click();});resize();if(new URLSearchParams(location.search).has('demo')){demoMode=true;start();}let prev=performance.now();function loop(now:number){const dt=Math.min(.035,(now-prev)/1000);prev=now;if(active&&!paused)step(dt);draw();requestAnimationFrame(loop);}requestAnimationFrame(loop);
Object.assign(window,{__cardrush:{state:()=>({tutorial,tutorialRound,phase,hand:[...hand],ammo:[...ammo],params:[...params],turn,kills,lives,wave,shotCount,emitted,stream:stream?{left:stream.left}:null,demo:demoMode,history:demoHistory,music:music.status(),projectiles:shots.map(s=>({pattern:s.pattern,age:s.age,card:s.card.id,x:s.x,y:s.y,index:s.index,detached:s.detached})),formation:formationName,shots:shots.length,pending:pending.length,enemies:enemies.map(e=>({x:e.x,y:e.y,hp:e.hp,kind:e.kind})),active,paused}),advance:(sec:number)=>{for(let i=0;i<sec*60&&active;i++)step(1/60);}}});

if(new URLSearchParams(location.search).has('qa'))Object.assign((window as unknown as {__cardrush:object}).__cardrush,{fixture:(cards:Card[],parameter:number,heavy:boolean)=>{shots.length=0;rings.length=0;enemies.length=0;stream=null;demoMode=false;for(let i=0;i<7;i++)enemies.push({x:W/2+(i-3)*28,y:H-230+(i%2)*30,hp:100,max:100,speed:0,seed:i,hit:0});hand=cards.map(c=>({...c,id:++serial}));ammo=[...hand];hand=[];pattern=analyze(ammo);params=[{id:++serial,rank:parameter,suit:0}];turn=heavy?1:0;phase='ready';updateUI();},fireTest:(angle:number)=>fire(angle)});

