import * as T from 'three';
export interface ImpactVisual{x:number;y:number;max:number;life:number;color:string;pattern?:string}
interface FX{mesh:T.Mesh;life:number;maxLife:number;vx:number;vy:number;vz:number;growth:number;spin:number;opacity:number;flat:boolean}
/** Layered, filled effects: flame volumes, light sprites, petal meshes, smoke and flying debris. */
export class VolumeFX{
 private fx:FX[]=[];private seen=new WeakSet<object>();private glow:T.CanvasTexture;private smoke:T.CanvasTexture;private flame:T.CanvasTexture;
 constructor(private scene:T.Scene){this.glow=this.texture(false);this.smoke=this.texture(true);this.flame=this.flameTexture();}
 private flameTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d')!;const flame=(scale:number,color:string)=>{x.save();x.translate(64,76);x.scale(scale,scale);x.beginPath();x.moveTo(-42,22);x.bezierCurveTo(-58,-6,-18,-20,-30,-54);x.quadraticCurveTo(-8,-45,-7,-23);x.quadraticCurveTo(14,-47,4,-72);x.quadraticCurveTo(48,-43,30,-19);x.quadraticCurveTo(49,-27,48,-48);x.bezierCurveTo(74,5,32,45,-8,38);x.closePath();x.fillStyle=color;x.fill();x.restore();};flame(1,'#a73920');flame(.84,'#f17623');flame(.58,'#ffc756');flame(.30,'#fff4c5');return new T.CanvasTexture(c);}
 private texture(smoke:boolean){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d')!,g=x.createRadialGradient(64,64,1,64,64,64);g.addColorStop(0,smoke?'rgba(255,255,255,.65)':'rgba(255,255,255,1)');g.addColorStop(smoke?.5:.18,smoke?'rgba(255,255,255,.45)':'rgba(255,255,255,.95)');g.addColorStop(.6,'rgba(255,255,255,.22)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new T.CanvasTexture(c);}
 private add(g:T.BufferGeometry,m:T.Material,x:number,y:number,z:number,life:number,vx=0,vy=0,vz=0,growth=0,spin=0,flat=false){if(this.fx.length>340){g.dispose();m.dispose();return;}const mesh=new T.Mesh(g,m);mesh.position.set(x,y,z);this.scene.add(mesh);this.fx.push({mesh,life,maxLife:life,vx,vy,vz,growth,spin,opacity:(m as T.MeshBasicMaterial).opacity,flat});}
 private light(x:number,y:number,size:number,color:number,life:number){this.add(new T.PlaneGeometry(size,size),new T.MeshBasicMaterial({map:this.glow,color,transparent:true,opacity:1,depthWrite:false,blending:T.AdditiveBlending}),x,y,60,life,0,0,0,1.6,0,true);}
 private petalGeometry(size:number){const s=new T.Shape();s.moveTo(0,-size*.45);s.bezierCurveTo(-size*.8,0,-size*.6,size*.85,0,size);s.bezierCurveTo(size*.6,size*.85,size*.8,0,0,-size*.45);return new T.ShapeGeometry(s,8);}
 impact(r:ImpactVisual,H:number){if(this.seen.has(r))return;this.seen.add(r);const x=r.x,y=H-r.y,p=r.pattern??'',flower=p.includes('flush'),blast=['bomb','chain-bomb','full-house','four-single','four-pair'].includes(p)||p.startsWith('airplane'),muzzle=r.y>H-65;
 if(muzzle){this.light(x,y,35,0xffddb0,.12);return;}
 const power=Math.min(1.7,r.max/75);this.light(x,y,blast?150*power:75*power,flower?0xffb8ef:0xfff1c3,.13);
 if(flower){for(let i=0;i<16;i++){const a=i*Math.PI*2/16;this.add(this.petalGeometry(12+power*6),new T.MeshStandardMaterial({color:i%2?0xe2578f:0xffb4ca,emissive:0x541a3e,roughness:.5,side:T.DoubleSide,transparent:true}),x,y,28,.75,Math.cos(a)*90,Math.sin(a)*90,40+Math.random()*60,.25,4);}}
 else if(blast){for(let i=0;i<10;i++){const a=i*Math.PI*2/10;this.add(new T.PlaneGeometry((40+Math.random()*20)*power,(48+Math.random()*24)*power),new T.MeshBasicMaterial({map:this.flame,color:0xffffff,transparent:true,opacity:1,depthWrite:false,side:T.DoubleSide}),x+Math.cos(a)*8,y+Math.sin(a)*8,25+Math.random()*20,.42+Math.random()*.15,Math.cos(a)*100*power,Math.sin(a)*100*power,30,1.4,0,true);}
 for(let i=0;i<7;i++){const a=i*Math.PI*2/7;this.add(new T.PlaneGeometry(55*power,55*power),new T.MeshBasicMaterial({map:this.smoke,color:0x4e3b42,transparent:true,opacity:.27,depthWrite:false}),x,y,10,.7,Math.cos(a)*65,Math.sin(a)*65,0,1.5,0,true);}
 const ring=new T.TorusGeometry(16*power,4*power,8,40);this.add(ring,new T.MeshBasicMaterial({color:0xffbb65,transparent:true,opacity:.85,depthWrite:false}),x,y,35,.3,0,0,0,5,0,true);
 }else{const a=p==='straight'||p==='pair-run'?-.5:.5;const shape=new T.Shape();shape.moveTo(-45*power,-4);shape.quadraticCurveTo(0,26*power,45*power,3);shape.quadraticCurveTo(0,8*power,-45*power,-4);this.add(new T.ShapeGeometry(shape),new T.MeshBasicMaterial({color:r.color,transparent:true,opacity:.9,side:T.DoubleSide}),x,y,35,.22,0,0,0,1,0,true);this.fx[this.fx.length-1]?.mesh.rotation.set(0,0,a);}
 for(let i=0;i<(blast?18:8);i++){const a=Math.random()*Math.PI*2,v=(90+Math.random()*120)*power;this.add(new T.TetrahedronGeometry((1.5+Math.random()*3)*power),new T.MeshStandardMaterial({color:i%3?0xe8aa59:0x46363f,emissive:i%3?0x703419:0,transparent:true}),x,y,35,.35+Math.random()*.25,Math.cos(a)*v,Math.sin(a)*v,70+Math.random()*100,0,8);}}
 update(dt:number){for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;f.mesh.position.x+=f.vx*dt;f.mesh.position.y+=f.vy*dt;f.mesh.position.z+=f.vz*dt;if(!f.flat){f.vz-=210*dt;f.mesh.rotation.x+=f.spin*dt;f.mesh.rotation.y+=f.spin*.7*dt;}f.mesh.scale.multiplyScalar(1+f.growth*dt);(f.mesh.material as T.MeshBasicMaterial).opacity=f.opacity*Math.pow(Math.max(0,f.life/f.maxLife),.65);if(f.life<=0){this.scene.remove(f.mesh);f.mesh.geometry.dispose();(f.mesh.material as T.Material).dispose();this.fx.splice(i,1);}}}
}
